package com.blockchainhandler.api.mapper;

import com.blockchainhandler.api.dto.TransferResponse;
import com.blockchainhandler.storage.entity.TransferEntity;
import java.util.List;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * Maps {@link TransferEntity} rows to API DTOs so JPA entities never leave the service layer.
 *
 * <p>The implementation is generated by MapStruct at compile time; unmapped target properties fail the build.
 */
@Mapper
public interface TransferMapper {

    /**
     * Maps a transfer row to its API representation.
     *
     * @param entity transfer row
     * @return transfer DTO
     */
    @Mapping(target = "transactionHash", source = "txHash")
    @Mapping(target = "tokenAddress", source = "contractAddress")
    @Mapping(target = "from", source = "fromAddress")
    @Mapping(target = "to", source = "toAddress")
    @Mapping(target = "value", source = "valueUsdc")
    @Mapping(target = "valueRaw", expression = "java(entity.getValueRaw().toPlainString())")
    TransferResponse toResponse(TransferEntity entity);

    /**
     * Maps transfer rows to their API representation, keeping the order.
     *
     * @param entities transfer rows
     * @return transfer DTOs
     */
    List<TransferResponse> toResponses(List<TransferEntity> entities);
}
